### ISSUE TITLE
calling  chartist update() method on this plugin

### ISSUE THREAD

**Issue by adriennn** [shbmbhrdwj/chartist-plugin-multithreshold#1]
Hello,

is there a way to include new defaultOptions when calling the .update() core method on a chart without rebuilding the chart from scratch?

**Comment by shbmbhrdwj** [comment]
Hi @adriennn sorry for the late reply, can you be more specific, as to what your needs are?

**Comment by adriennn** [comment]
hi @shbmbhrdwj and thank for the reply,

I would like to know if it's possible to pass a new array of threshold values when using chartist-js's core `.update()` method?
Something along the line (untested):
`mygraph.update({threshold: [0, 10, 25]})`

**Comment by shbmbhrdwj** [comment]
No, I am afraid, it is not possible as of now, but yes I can take this up this weekend, meanwhile if you feel like it, you can raise a PR for same, thanks

**Comment by shbmbhrdwj** [comment]
@adriennn Done, thanks for bringing it forward
